### ISSUE TITLE
Matte quality

### ISSUE THREAD

**Issue by lillekemiker** [Serge-weihao/TMF-Matting#2]
I am trying to use your pretrained model for image matting but my results are nowhere near as good as what you show in your publication. Would you mind taking a look and maybe provide some feedback on what I am doing wrong? It would be very much appreciated.

I am using your `TMF_comp1k` model checkpoint and running it either with our without TTA. This is the command with:
```
python demo/matting_demo.py \
    configs/mattors/gradloss/tmflaploss020tta8.py \
    ./TMF_Matting_comp1k.pth \
    ./bird.png \
    ./trimap.png \
    ./matte_tta.png
```

You can see my input images below as well as two images where I have used the alpha matte to substitute the background for a black, blue or white solid color. The first result is with TTA and the second is without.

The two results are pretty similar but neither gives me a very tight crop. What am I doing wrong?

Thank you in advance.

![bird](https://github.com/Serge-weihao/TMF-Matting/assets/11468493/c023a4be-32f3-4a08-934a-7c1069b54f6c)
![trimap](https://github.com/Serge-weihao/TMF-Matting/assets/11468493/0d30fe4c-25d1-47e1-9f1d-2ea4eabedda6)
![TMF_matte_applied](https://github.com/Serge-weihao/TMF-Matting/assets/11468493/45e7ee83-1610-413a-a5d2-c9056d317b78)
![TMF_matte_tta_applied](https://github.com/Serge-weihao/TMF-Matting/assets/11468493/c91cdf2c-0a9a-41eb-9514-c5def3f1d569)

**Comment by Serge-weihao** [comment]
![image](https://github.com/Serge-weihao/TMF-Matting/assets/40890323/99ceb401-b551-492f-ac79-40001cd080d8)

**Comment by Serge-weihao** [comment]
> ![image](https://user-images.githubusercontent.com/40890323/277932742-99ceb401-b551-492f-ac79-40001cd080d8.png)
Can you see the mosaic-like regions around the foreground objects in your input image? I think your input image has been processed by some rough matting or extraction process (maybe photoshop) to remove background of the original image captured by camera, and that  process produced the mosaic-like regions in your input image.  And I assume that those strange regions lead to the untight crop, because these regions are strange for  the traning set.

**Comment by Serge-weihao** [comment]
> ![image](https://user-images.githubusercontent.com/40890323/277932742-99ceb401-b551-492f-ac79-40001cd080d8.png)

cropped from the top image in your comment

**Comment by lillekemiker** [comment]
Ah yes, I see it. That is a good catch. Looks like jpeg artifacts, I think. Maybe the model training data was all higher quality images.
Thanks for taking a look. I can confirm that the model does seem to work very well for me on higher quality images.
